# Horizontal Pod Autoscaler for MAXIMUS Core
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: maximus-core-hpa
  namespace: maximus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: maximus-core
  minReplicas: 3
  maxReplicas: 10
  metrics:
    # CPU-based scaling
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    # Memory-based scaling
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
---
# HPA for PENELOPE
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: penelope-hpa
  namespace: maximus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: penelope
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
